In [15]:
import numpy as np



In [18]:
a=np.empty((10,2))
len(a)

10

In [8]:
pred_indexes

array([[ 1., 21.],
       [ 2., 22.],
       [ 3., 23.],
       [ 4., 24.],
       [ 5., 25.],
       [ 6., 26.],
       [ 7., 27.],
       [ 8., 28.],
       [ 9., 29.],
       [10., 30.],
       [11., 31.],
       [12., 32.],
       [13., 33.],
       [14., 34.],
       [15., 35.],
       [16., 36.],
       [17., 37.],
       [18., 38.],
       [19., 39.],
       [20., 40.]])

In [18]:
window_size=4
stride=4
fs=1
y_exp=[1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,6,6,6,6]
n_samples=12
n_ext_samples=len(y_exp)
y_exp=np.hstack([y_exp,np.zeros(shape=50)])
window_pts = int(window_size * fs)
stride_pts = int(stride * fs)
print(window_pts,stride_pts)

out=np.zeros(shape=(n_samples))
i=0
ad=int(n_ext_samples/(stride_pts*n_samples))
for sample in range(0,n_ext_samples,stride_pts):
    print(sample)
    print(np.mean(y_exp[sample:sample+window_pts]))
    out[i*ad:(i+1)*ad]=np.mean(y_exp[sample:sample+window_pts])
    i+=1
    if i>=n_samples:
        break
out

4 4
0
1.0
4
2.0
8
3.0
12
4.0
16
5.0
20
6.0


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
y_exp[:20]

array([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4., 5.,
       5., 5., 5.])

In [12]:
print(x.predict_proba)

<bound method BaseSearchCV.predict_proba of GridSearchCV(estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     callbacks=None, colsample_bylevel=1,
                                     colsample_bynode=1, colsample_bytree=1,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     gamma=0, gpu_id=-1, grow_policy=None,
                                     importance_type='gain',
                                     interaction_constraints='',
                                     learning_rate=0.005, max_bin=None,
                                     max_cat_to_onehot=Non...
                                     max_depth=6, max_leaves=None,
                                     min_child_weight=1, missing=nan,
                                     monotone_constraints='()',
                                     n_estimators=10